- hosts: all
  tasks:
  - copy:
      content: "Development"
      dest: "/etc/issue"
    when: inventory_hostname in groups['dev'] or inventory_hostname in groups['test']

  - copy:
      content: "Production"
      dest: "/etc/issue"
    when: inventory_hostname in groups['prod']
